Models/Comment.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AlphaBlogging.Models
{
    public class Comment
    {
        [Required]
        public int Id { get; set; }

        [Required, Display(Name = "Content")]
        [StringLength(512)]
        public string Body { get; set; }

        [Required]
        public DateTime Created { get; set; }

        [Required]
        public DateTime Updated { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public int PostId { get; set; }

        public virtual Post Post { get; set; }

        public Comment()
        {
            
        }

        public Comment(string body, ApplicationUser author, int postId)
        {            
            Body = body;
            Created = DateTime.Now;
            Author = author;
            PostId = postId;
        }
    }
}

Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using AlphaBlogging.Services;
using System.Threading.Tasks;
using AlphaBlogging.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AlphaBlogging.Data;
using AlphaBlogging.Data.Repos;
using System.Net.Http;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Text;
using Microsoft.AspNetCore.Hosting;


namespace AlphaBlogging.Controllers
{
    //[Authorize(Roles = "Superadmin, Admin, Author")]
    public class BlogController : Controller
    {
        //Dependency Inject of BlogService and SignIn
        private readonly IUserServices _userServices;
        private readonly IBlogsServices _bloggyService;
        private readonly IPostServices _postService;
        private static readonly HttpClient httpClient = new();
        private readonly HttpRequestSettings _requestSettings;
        public BlogController(
            IUserServices userServices,
            IPostServices posty,
            IBlogsServices bloggy,
            IOptions<HttpRequestSettings> requestSettings
            )

        {
            _bloggyService = bloggy;
            _postService = posty;
            _userServices = userServices;
            _requestSettings = requestSettings.Value;
        }

        public IActionResult PostArchive(int id)
        {
            var query = _postService.GetPostsByDate(id);
                return View(query);
        }
        public ApplicationUser GetSignedInId()
        {
            //var signedIn = _signInManager.IsSignedIn(User);
            var user = User.Identity.Name;

            ApplicationUser authorId = _userServices.GetCurrentApplicationUser(user);

            return authorId;
        }

        [Authorize(Roles = "Superadmin, Admin")]
        public IActionResult Bloglist()
        {
            var blogs = _bloggyService.GetAllBlogs();
            return View(blogs);

        }

        [Authorize(Roles = "Superadmin, Admin, Author")]
        public IActionResult MyBloglist()
        {
            
            //var user = User.Identity.Name;

            ApplicationUser authorId = GetSignedInId();

            var blogs = _bloggyService.GetMyBlogs(authorId);

            //var query = (from blogItem in blogs
            //            where blogItem.Author == authorId
            //            select blogItem).ToList();            

            return View(blogs);

        }


        //[Authorize]
        public IActionResult BlogView(int id)
        {           
            var blog = _bloggyService.GetBlog(id);
            _bloggyService.IncreaseViewCountOfAllPostsInBlog(id);
            return View(blog);  
        }

        //public IActionResult BlogPostView(int Id)
        //{
        //    //var blog = _bloggyService.GetPostsFromBlogID(Id);
        //    return View();
        //}


        //[Authorize]
        //[HttpGet]
        //public IActionResult CreateBlog()
        //{

        //    return View(new Blog());
        //}


        //[Authorize]
        //[HttpPost]
        //public async Task<IActionResult> CreateBlog(Blog blog)
        //{
        //    blog.Author = GetSignedInId();
        //    // _bloggyService.AddImage(blog);

        //    Blog bloggy = new Blog(blog.Title, blog.Description, blog.Body, blog.BlogImage, blog.ImageFile, blog.Author, blog.Visible = true);

        //    _bloggyService.AddBlog(bloggy);

        //    if (await _bloggyService.SaveChangesAsync())

        //        if (User.IsInRole("Admin") || User.IsInRole("Superadmin"))
        //        {
        //            return RedirectToAction("Bloglist");
        //        }
        //    return RedirectToAction("MyBloglist");

        //}

        [Authorize]
        [HttpGet]
        public IActionResult CreateBlog()
        {
            return View(new Blog());
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateBlog(Blog blog)
        {
            blog.Author = GetSignedInId();
            if (blog.ImageFile != null)
                _bloggyService.AddImage(blog);

            Blog bloggy = new(blog.Title, blog.Description, blog.Body, blog.BlogImage, blog.ImageFile, blog.Author, blog.Visible = true);

            _bloggyService.AddBlog(bloggy);

            if (await _bloggyService.SaveChangesAsync())

            {
                string userEmail = _userServices.GetAuthorEmail(User.Identity.Name);

                ConfirmMessage sendMsg = new()
                {
                    Email = userEmail,
                    MobileNumber = "0",
                    BlogTitle = blog.Title,
                    ConfirmText = "<html><body><h2>Dear " + User.Identity.Name
                    + "!</h2><h3> Your blog " + blog.Title + " is now ready to use!</h3>"
                };

                TempData["EmailStatus"] = await SendConfirmation(sendMsg);

                //return RedirectToAction("BlogView", new { id = blog.Id });

                if (User.IsInRole("Admin") || User.IsInRole("Superadmin"))
                {
                    return RedirectToAction("Bloglist");
                }

                return RedirectToAction("MyBloglist");
            }
            else
                return View(bloggy);


            //if (await _bloggyService.SaveChangesAsync())
            //    if (User.IsInRole("Admin") || User.IsInRole("Superadmin"))
            //    {
            //        return RedirectToAction("Bloglist");
            //    }
            //return RedirectToAction("MyBloglist");

            //    return RedirectToAction("BlogView", new { id = blog.Id });
            //else
            //    return View(bloggy);
        }


        private async Task<string> SendConfirmation(ConfirmMessage sendMsg)
        {
            //string funcUrl = "https://alphablogqueuefunction.azurewebsites.net/api/HttpTrigger1?code=54KCQAvWXKb6qcuogze/uNfIlwnaQUpz120AiNjQI5VD/3ogmqla7Q==";
            string funcUrl = _requestSettings.MyAzureFunctionUrl;  //Azure url
            //string funcUrl = _requestSettings.MyLocalFunctionUrl;  // For testing function locally(localhost://)
            string statusMsg = "";

            using (var myrequest = new HttpRequestMessage(HttpMethod.Post, funcUrl))
            {
                var json = JsonConvert.SerializeObject(sendMsg);
                var httpContent = new StringContent(json, Encoding.UTF8, "application/json");
                myrequest.Content = httpContent;

                using var newresponse = await httpClient
                    .SendAsync(myrequest)
                    .ConfigureAwait(false);
                if (newresponse.IsSuccessStatusCode)
                {
                    statusMsg = "Your blog has been created. A confirmation has been sent by email.";
                }
                else
                    statusMsg = "Ooops!";
            }
            return statusMsg;
        }



        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new Blog());
            }
            else
            {
                var blog = _bloggyService.GetBlog((int)id);

                if (User.IsInRole("Superadmin") || User.IsInRole("Admin") || blog.Author.UserName == User.Identity.Name)
                {
                    return View(blog); 
                }
            }
            return View("NotFound");

            //if (id == null)
            //    return View(new Blog());
            //else
            //{
            //    var blog = _bloggyService.GetBlog((int)id);
            //    return View(blog);
            //}
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(Blog blog)
        {
            if (blog.Id > 0) 
            {
                //_bloggyService.AddImage(blog);
                _bloggyService.UpdateBlog(blog);
            }
            else
            {
                //_bloggyService.AddImage(blog);
                _bloggyService.AddBlog(blog);
            }

            if (await _bloggyService.SaveChangesAsync())
                return RedirectToAction("BlogView", new { id = blog.Id });
            else
                return RedirectToAction("Edit");
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            var blog = _bloggyService.GetBlog((int)id);

            if (User.IsInRole("Admin") || User.IsInRole("Superadmin") || blog.Author.UserName == User.Identity.Name)
            {
                _bloggyService.DeleteBlog(id);
                await _bloggyService.SaveChangesAsync();
            }

            if (User.IsInRole("Admin") || User.IsInRole("Superadmin"))
            {
                return RedirectToAction("Bloglist");
            }
            return RedirectToAction("MyBloglist");

            //_bloggyService.DeleteBlog(id);
            //await _bloggyService.SaveChangesAsync();
            //if (User.IsInRole("Admin") || User.IsInRole("Superadmin"))
            //{
            //    return RedirectToAction("Bloglist");
            //}
            //    return RedirectToAction("MyBloglist");
        }

    }
}

Controllers/CommentController.cs
using AlphaBlogging.Data.Repos;
using AlphaBlogging.Models;
using AlphaBlogging.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AlphaBlogging.Data;
using System.Threading.Tasks;
using System.Linq;
using System.Net.Http;
using System.Text;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace AlphaBlogging.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {

        private readonly ICommentServices _commentService;
        private readonly IUserServices _userServices;
        private readonly ISMSServices _smssService; 
        private readonly ApplicationDbContext _db;
        private static readonly HttpClient httpClient = new();
        private readonly HttpRequestSettings _requestSettings;

        public CommentController(
            IOptions<HttpRequestSettings> requestSettings,
            ICommentServices commentService, 
            ISMSServices smssService, 
            IUserServices userServices, 
            ApplicationDbContext context
            )
        {

            _commentService = commentService;
            _userServices = userServices;
            _smssService = smssService;
            _db = context;
            _requestSettings = requestSettings.Value;
        }

        [Authorize(Roles = "Superadmin, Admin, Author")]
        public IActionResult CommentList()        {
            
            var comments = _commentService.GetAllComments();
            return View(comments);
        }

        public IActionResult CommentView (int id)
        {
            var comment = _commentService.GetComment(id);
            return View(comment);
        }

        
        [HttpGet]
        public IActionResult Create(int postId)
        {
            return View(new Comment() { PostId = postId});
        }

        
        [HttpPost]
        public async Task<IActionResult> Create(Comment comment)
        {
                var user = User.Identity.Name;

                Comment newComment = new(comment.Body, _userServices.GetCurrentApplicationUser(user), comment.PostId);

                _commentService.AddComment(newComment);


                if (await _commentService.SaveChangesAsync())
                    return RedirectToAction("PostView", "Post",new {id = comment.PostId});
                    //return RedirectToAction("BlogView", "Blog", new { Id = post.BlogId });

                else
                    return View(newComment);
            
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0)
                return View(new Comment());
            else
            {
                var comment = _commentService.GetComment((int)id);
                return View(comment);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Comment comment)
        {
            var user = User.Identity.Name;

            if (comment.Id > 0)
            {
                comment.Author = _userServices.GetCurrentApplicationUser(user);
                _commentService.UpdateComment(comment);
            }
            
            else
            {
                _commentService.AddComment(comment);
            }


            if (await _commentService.SaveChangesAsync())
                return RedirectToAction("PostView","Post",new { Id = comment.PostId});

            else
                return View(comment);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int commentId)
        {

            // Commenting the SMS functionality below. It works but sends me a SMS for each deleted comment. Anoying!!!!

            //int introLength = 10;
            //string userName = _commentService.GetCommentOwner(commentId);
            //string commentStart = _commentService.GetFirstPartOfComment(commentId, introLength);
            ////string mobileNum = _userServices.GetAuthorMobile(userName);

            //var sendMsg = "Dear " + userName + "\nYour comment \"" + commentStart + "\" has been erased due to infringement of the site rules!";

            //_smssService.SendSMS(sendMsg);

            //TempData["EmailStatus"] = await SendSMSToCommenter(sendMsg);

            var entry = _db.Comments.Single(r => r.Id == commentId);
            _commentService.DeleteComment(commentId);
            await _commentService.SaveChangesAsync();
            return RedirectToAction("PostView", "Post", new { id = entry.PostId });

        }


        private async Task<string> SendSMSToCommenter(string sendMsg)
        {

            //string funcUrl = _requestSettings.MyAzureSMSUrl;  //Azure url
            string funcUrl = _requestSettings.MyLocalSMSUrl;  // For testing function locally(localhost://)
            string statusMsg = "";

            using (var myrequest = new HttpRequestMessage(HttpMethod.Post, funcUrl))
            {
                var json = JsonConvert.SerializeObject(sendMsg);
                var httpContent = new StringContent(json, Encoding.UTF8, "application/json");
                myrequest.Content = httpContent;

                using (var newresponse = await httpClient
                    .SendAsync(myrequest)
                    .ConfigureAwait(false))
                {
                    if (newresponse.IsSuccessStatusCode)
                    {
                        statusMsg = "The comment has been created. A message has been sent by SMS to the commenter.";
                    }
                    else
                        statusMsg = "Ooops!";
                }
            }
            return statusMsg;
        }
    }
}

Controllers/SearchController.cs
using AlphaBlogging.Data.Repos;
using AlphaBlogging.Models;
using AlphaBlogging.Models.ViewModels;
using AlphaBlogging.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace AlphaBlogging.Controllers
{
    public class SearchController : Controller
    {

        private ISearchServices _searchservice;
        private IBlogsServices _blogsServices;
        private IPostServices _postServices;


        public SearchController(ISearchServices searchservice, IBlogsServices blogsServices, IPostServices postServices)
        {
            _searchservice = searchservice; 
            _blogsServices = blogsServices;
            _postServices = postServices; 
        }

        //[HttpGet]
        //public IActionResult Search()
        //{            
            
        //    return View();
        //}

     
        //public IActionResult Search(string searchTerm)
        //{

        //    return RedirectToAction("SearchResult",new { searchTerm = searchTerm });
        //}
        //[HttpGet]
        public IActionResult SearchResult(string searchTerm)
        {

            var blogResults = _searchservice.FindBlogsByTerm(searchTerm);
            var postsResults = _searchservice.FindPostsByTerm(searchTerm);
            var tagResults = _searchservice.FindTagsByTerm(searchTerm);
            var result = new SearchResultsVM(searchTerm, blogResults, postsResults, tagResults);
            return View(result);
        }
    }
}

Views/Shared/NotFound.cshtml
@using AlphaBlogging.Models;

@{
    ViewBag.Title = "Not found";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

@*@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-warning" role="alert">
        @ViewBag.ErrorMessage
    </div>
}*@

<div class="container-fluid px-4">
        <br /><br />
    <div style="text-align: center;">
        <h3 class="text-danger">Oops!</h3><br />
        <i class="far fa-flushed fa-9x text-secondary"></i>
        <br /><br />
        <h1 class="text-danger">@ViewData["Title"]</h1>
        <h4 class="text-danger">You do not have access to this resource.</h4>
    </div>


@*    <br />
    <div>
        <h4>The resource you are looking for cannot be found.</h4>
            <a asp-page="/Admin" class="btn btn-primary">
            return
            </a>
    </div>*@
</div>

Views/Shared/_AdminFooterPartial.cshtml
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; 2022 AlphaBlogging</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

Views/Shared/_AdminSideNavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <br />
            @*<a class="nav-link" asp-controller="Admin" asp-action="Index">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>*@
            @if(SignInManager.IsSignedIn(User) && User.IsInRole("Superadmin"))
            {
                <a class="nav-link" asp-controller="Blog" asp-action="Bloglist">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Manage all blogs
                </a>
                <a class="nav-link" asp-controller="ManageUsers" asp-action="Index">
                <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                Manage users
                </a>
                <a class="nav-link" asp-controller="RoleManager" asp-action="Index">
                <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                Create user roles
                </a>
                <a class="nav-link" asp-controller="Post" asp-action="Postlist">
                <div class="sb-nav-link-icon"><i class="fas fa-edit"></i></div>
                Manage post
                </a>
                <a class="nav-link" asp-controller="Comment" asp-action="CommentList">
                <div class="sb-nav-link-icon"><i class="fas fa-comments"></i></div>
                Manage Comment
                </a>
            }
            @if(SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <a class="nav-link" asp-controller="Blog" asp-action="Bloglist">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Manage all blogs
                </a> 
            }
            @if(SignInManager.IsSignedIn(User) && User.IsInRole("Author"))
            {
                <a class="nav-link" asp-controller="Blog" asp-action="MyBloglist">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Manage my blog
                </a> 
            }
            <div class="d-4 d-md-inline-block form-inline ms-3 me-3 me-md-3 my-2 my-md-0 pt-3"><partial name="_Search" /></div>
            @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Manage blog
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" asp-controller="Blog" asp-action="Create">Create blog</a>
                    <a class="nav-link" asp-controller="Blog" asp-action="Edit">Edit blog</a>
                </nav>
            </div>*@
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        @((await UserManager.GetUserAsync(User)).UserName)
    </div>
</nav>

Views/Shared/_AdminTopNavPartial.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" asp-controller="Home" asp-action="Index">AlphaBlogging</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <div class="d-4 d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0 pt-3"> </div>
@*    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>*@
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">Settings</a></li>
                @*<li><hr class="dropdown-divider" /></li>*@

                <li><a class="dropdown-item" onclick="javascript:document.getElementById('LogoutForm').submit();" style="cursor: pointer;">Logout</a></li>
                <form class="form-inline" id="LogoutForm" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                </form>
            </ul>
        </li>
    </ul>
</nav>

Views/Shared/_Comment.cshtml
@model AlphaBlogging.Models.Comment

@{
    ViewData["Title"] = "Comment";
}

<div>
    @*<h6>Comment</h6>*@
    <p class="created">Comment @Model.Created.ToShortDateString() by @Model.Author.UserName</p>
    <p>@Model.Body</p>

    @if (User.IsInRole("Superadmin") || User.IsInRole("Admin") || User.IsInRole("Author") || User.IsInRole("User"))
    {
@*        @Html.ActionLink("Add Comment", "Create", "Comment", new {postId = Model.Id} )
*@          }
    @if (Model.Author.UserName == User.Identity.Name || User.IsInRole("Superadmin"))
    {
        @Html.ActionLink("Edit Comment", "Edit", "Comment", new {id = Model.Id} ) @: |
       @Html.ActionLink("Delete Comment", "Remove", "Comment", new {commentId = Model.Id} )
    }

   

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlphaBlogging</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/styles.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://kit.fontawesome.com/d47a02d96e.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <button onclick="topFunction()" id="myBtn" title="Back to top"><i class="fas fa-arrow-alt-circle-up"></i></button>  
    <div id="earth" class="earth">
        <div class="moon">
            <header class="bg-transparent">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-transparent  border-bottom box-shadow mb-3">
                    <div class="container">
                        <a class="navbar-brand-logo" asp-area="" asp-controller="Home" asp-action="Index">&#64;</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse  d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                               @if (User.IsInRole("SuperAdmin")||User.IsInRole("Admin")||User.IsInRole("Author")){
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Blog" asp-action="CreateBlog">Create new Blog</a>
                                </li>
                               }
                                @if (User.IsInRole("SuperAdmin")||User.IsInRole("Admin")){
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Blog" asp-action="Bloglist">List of Blogs</a>
                                </li>                               
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="Postlist">List of posts</a>
                                </li>
                                }
                                                          
                            </ul>
                            <div class="pt-3"><partial name="_Search" /></div>
                            <div class=""><partial name="_LoginPartial" /></div>
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container ">
                <main role="main" class="pb-3 col-lg-12 col-md-12 col-sm-12 col-xs-12 align-content-center ">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AlphaBlogging - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/custom.js" asp-append-version="true"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Search.cshtml
@*@model AlphaBlogging.Models.ViewModels.SearchResultsVM*@


@*<ul class="navbar-nav">*@
@*<li class="input-group" style="width:300px;">
    <form asp-controller="Search" asp-action="SearchResult">
        <input name="searchTerm" id="searchTerm" class="form-control" style="width:200px" />
        <div class="input-group-append">
            <input type="submit" value="Search" class="btn btn-primary" style="width:50px"/>
        </div>
    </form>
</li>*@
<form method="get" asp-controller="Search" asp-action="SearchResult">
<div class="input-group mb-3">
  <input type="text" name="searchTerm" id="searchTerm" class="form-control bg-dark text-light" placeholder="..." aria-label="..." aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button type="submit" class="btn btn-outline-secondary text-light" type="button">Search</button>
  </div>
</div>
</form>
@*</ul>*@

@* <div class="input-group rounded">
    <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
    aria-describedby="search-addon" method="post" asp-controller="Search" asp-action="Search"/>
    <span class="input-group-text border-0" id="search-addon">
    </span>
    </div>*@

Views/Shared/_TagPartial.cshtml
@model AlphaBlogging.Models.Tag

<div class="tag" >

    <span class="btn btn-bg-transparent text-white-50">#@Model.HashTag</span>

</div>

@*<button type = "button" class = "btn btn-primary btn-xs">
      Extra small Primary button
   </button>*@