Controllers/ManageUsersController.cs
using AlphaBlogging.Models;
using AlphaBlogging.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlphaBlogging.Controllers
{
    [Authorize(Roles = "Superadmin")]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageUsersController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesVM = new List<UserRolesVM>();
            foreach (ApplicationUser user in users)
            {
                var thisViewModel = new UserRolesVM();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.FirstName = user.FirstName;
                thisViewModel.LastName = user.LastName;
                thisViewModel.UserName= user.UserName;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesVM.Add(thisViewModel);
            }
            return View(userRolesVM);
        }

        private async Task<List<string>> GetUserRoles(ApplicationUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

        public async Task<IActionResult> Manage(string UserId)
        {
            ViewBag.userId = UserId;
            var user = await _userManager.FindByIdAsync(UserId);
            if (user == null)
            {
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesVM>();
            foreach (var role in _roleManager.Roles)
            {
                var userRolesVM = new ManageUserRolesVM
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesVM.Selected = true;
                }
                else
                {
                    userRolesVM.Selected = false;
                }
                model.Add(userRolesVM);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesVM> model, string UserId)
        {
            var user = await _userManager.FindByIdAsync(UserId);

            if (user == null)
            {
                return View();
            }

            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string UserId)
        {
            var user = await _userManager.FindByIdAsync(UserId);

            if (user == null)
            {
                return View("NotFound");
            }

            var model = new UserRolesVM
            {
                UserId = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserName = user.UserName,
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserRolesVM model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                return View("NotFound");
            }
            else
            {
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;
                user.UserName = model.UserName;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

       
        public async Task<IActionResult> Delete(string UserId)
        {
            var user = await _userManager.FindByIdAsync(UserId);

            if (user == null)
            {
                return View("NotFound");
            }
            else
            {
                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("Index");
            }
        }
    }
}

Views/ManageUsers/Edit.cshtml
@model AlphaBlogging.Models.ViewModels.UserRolesVM


@{
    ViewBag.Title = "Edit User";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid px-4">
    <br />
<h1>Edit User</h1>
    <form method="post" class="mt-3">
        
        <div class="form-group row">
            <label asp-for="UserId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="UserId" disabled class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="FirstName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstName" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="UserName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="UserName" class="form-control">
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </div>
    </form>
</div>

Views/ManageUsers/Index.cshtml
@model List<AlphaBlogging.Models.ViewModels.UserRolesVM>

@{
    ViewData["Title"] = "Manage users";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid px-4">
    <br />
    <h1>Manage users</h1>
    <a class="btn btn-primary" href='/Identity/Account/Register'><i class="fas fa-pen"></i> Create new user</a>
    <br /><br />
    <table id="datatablesSimple">
        <thead>
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.FirstName @user.LastName</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td>@string.Join(" ,", user.Roles.ToList())</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Action
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-controller="ManageUsers" asp-action="Edit" asp-route-userId="@user.UserId">Edit</a></li>
                                <li><a class="dropdown-item" asp-controller="ManageUsers" asp-action="Manage" asp-route-userId="@user.UserId">Manage Roles</a></li>
                                <li><a class="dropdown-item" asp-controller="ManageUsers" asp-action="Delete" asp-route-userId="@user.UserId" 
                                     onclick="return confirm('Are you sure you want to delete @user.UserName?')">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/ManageUsers/Manage.cshtml
@model List<AlphaBlogging.Models.ViewModels.ManageUserRolesVM>
@{
    ViewData["Title"] = "Manage user roles";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid px-4">
    <br />
<form method="post">
    <div class="card">
        <div class="card-header">
            <h1>Manage user roles</h1>
            <h5>Add/remove roles for user: @ViewBag.UserName</h5>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId" />
                    <input type="hidden" asp-for="@Model[i].RoleName" />
                    <input asp-for="@Model[i].Selected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].Selected">
                        @Model[i].RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary"
                   style="width:auto" />
            <a asp-action="Index" asp-controller="ManageUsers"
               class="btn btn-secondary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>
</div>