Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace AlphaBlogging.Controllers
{
    [Authorize(Roles = "Superadmin")]
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return View("NotFound");
            }
            else
            {
                var result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("Index");
            }
        }
    }
}

Views/RoleManager/Index.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Role Manager";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid px-4">
    <br />
    <h1>Create user role</h1>
    <form method="post" asp-action="AddRole" asp-controller="RoleManager">
        <div class="input-group">
            <input name="roleName" class="form-control w-25">
            <span class="input-group-btn">
                <button class="btn btn-primary">Add New Role</button>
            </span>
        </div>
    </form>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Role</th>
                <th>Id</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model)
            {
                <tr>
                    <td>@role.Name</td>
                    <td>@role.Id</td>
                    <td>
                        <form method="post" asp-action="DeleteRole" asp-route-id="@role.Id">
                        <button type="submit" class="btn btn-primary btn-sm"
                         onclick="return confirm('Are you sure you want to delete @role.Name?')">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>